//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativeViewerGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NearestNeighbor")]
        public global::System.Drawing.Drawing2D.InterpolationMode InterpModeStretch {
            get {
                return ((global::System.Drawing.Drawing2D.InterpolationMode)(this["InterpModeStretch"]));
            }
            set {
                this["InterpModeStretch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HighQualityBilinear")]
        public global::System.Drawing.Drawing2D.InterpolationMode InterpModeShrink {
            get {
                return ((global::System.Drawing.Drawing2D.InterpolationMode)(this["InterpModeShrink"]));
            }
            set {
                this["InterpModeShrink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640, 480")]
        public global::System.Drawing.Size AutoSizeMax {
            get {
                return ((global::System.Drawing.Size)(this["AutoSizeMax"]));
            }
            set {
                this["AutoSizeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160, 120")]
        public global::System.Drawing.Size AutoSizeMin {
            get {
                return ((global::System.Drawing.Size)(this["AutoSizeMin"]));
            }
            set {
                this["AutoSizeMin"] = value;
            }
        }
    }
}
